{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b5518fd6",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "from selenium import webdriver\n",
    "from time import sleep\n",
    "import csv\n",
    "from selenium.webdriver.common.by import By\n",
    "from bs4 import BeautifulSoup\n",
    "#from selenium.webdriver.firefox.options import Options\n",
    "#options = Options()\n",
    "#options.headless = True \n",
    "\n",
    "#from selenium.webdriver.firefox.options import Options as FirefoxOptions\n",
    "#from selenium import webdriver\n",
    "\n",
    "# options = FirefoxOptions()\n",
    "# options.add_argument(\"--headless\")\n",
    "\n",
    "\n",
    "\n",
    "driver = webdriver.Chrome()\n",
    "#IGEST\n",
    "driver.get('https://app.powerbi.com/view?r=eyJrIjoiYjExZGVmZTgtNjU0NC00MDAwLWJkYzgtNThlYjQwYTJhMDNhIiwidCI6IjYxOGE5ZWVkLWYxM2MtNDU4Ny1iODgzLTAwNWZiY2Q4N2FlZCJ9')\n",
    "sleep(6)\n",
    "soup = BeautifulSoup(driver.page_source, 'html.parser')\n",
    "IGEST = soup.find('tspan').text\n",
    "#HALO\n",
    "driver.get('https://app.powerbi.com/view?r=eyJrIjoiMmNlMTIzOWMtODJhNC00ZjYyLTlhMmEtMTJiN2RhMDZhYWVjIiwidCI6IjYxOGE5ZWVkLWYxM2MtNDU4Ny1iODgzLTAwNWZiY2Q4N2FlZCJ9')\n",
    "sleep(8)\n",
    "soup = BeautifulSoup(driver.page_source, 'html.parser')\n",
    "HALO = soup.find_all('g')[-2].text\n",
    "#HERMES\n",
    "driver.get('https://app.powerbi.com/view?r=eyJrIjoiMmQ0NmE2ZjUtNjRkMi00ZjI3LWFlM2QtN2RhNGJmYTBjMjFlIiwidCI6IjYxOGE5ZWVkLWYxM2MtNDU4Ny1iODgzLTAwNWZiY2Q4N2FlZCJ9')\n",
    "sleep(8)\n",
    "soup = BeautifulSoup(driver.page_source, 'html.parser')\n",
    "HERMES = soup.find_all('g')[-2].text\n",
    "#AÇÕES\n",
    "driver.get('https://app.powerbi.com/view?r=eyJrIjoiMmUzMDJiYTgtYjFjZS00ODVmLWIxMmUtNGFhMTc5MmIyNjAyIiwidCI6IjYxOGE5ZWVkLWYxM2MtNDU4Ny1iODgzLTAwNWZiY2Q4N2FlZCJ9')\n",
    "sleep(6)\n",
    "soup = BeautifulSoup(driver.page_source, 'html.parser')\n",
    "ACOES = soup.find_all('tspan')[-1].text\n",
    "#AÇÕES PJE\n",
    "driver.get('https://app.powerbi.com/view?r=eyJrIjoiMmUzMDJiYTgtYjFjZS00ODVmLWIxMmUtNGFhMTc5MmIyNjAyIiwidCI6IjYxOGE5ZWVkLWYxM2MtNDU4Ny1iODgzLTAwNWZiY2Q4N2FlZCJ9')\n",
    "sleep(6)\n",
    "soup = BeautifulSoup(driver.page_source, 'html.parser')\n",
    "ACOESPJE = soup.find_all('tspan')[-1].text\n",
    "#TRT 7 EM NÚMEROS\n",
    "driver.get('https://app.powerbi.com/view?r=eyJrIjoiNTZhZTIzY2QtMGY2My00NDZkLWE4MDUtMWI3Y2ViMTRiNzQ5IiwidCI6IjYxOGE5ZWVkLWYxM2MtNDU4Ny1iODgzLTAwNWZiY2Q4N2FlZCJ9')\n",
    "sleep(8)\n",
    "soup = BeautifulSoup(driver.page_source, 'html.parser')\n",
    "TRT7 = soup.find_all('tspan')[-1].text\n",
    "#Relatório de desempenho IGEST\n",
    "driver.get('https://igest.shinyapps.io/home/')\n",
    "sleep(10)\n",
    "soup = BeautifulSoup(driver.page_source, 'html.parser')\n",
    "RDIGEST = soup.find_all('strong')[1].text\n",
    "#Pendentes de solução\n",
    "driver.get('https://trt7.shinyapps.io/pendentes_de_soluo/')\n",
    "sleep(10)\n",
    "soup = BeautifulSoup(driver.page_source, 'html.parser')\n",
    "PENDESOL = soup.find_all('strong')[1].text\n",
    "#Aptos a Julgamento\n",
    "driver.get('https://app.powerbi.com/view?r=eyJrIjoiYjliODY4ZWUtOTZkYy00MjE0LWI1N2MtYzEyYTJkODRkZTJiIiwidCI6IjYxOGE5ZWVkLWYxM2MtNDU4Ny1iODgzLTAwNWZiY2Q4N2FlZCJ9')\n",
    "sleep(6)\n",
    "soup = BeautifulSoup(driver.page_source, 'html.parser')\n",
    "APTOS = soup.find_all('text')[0].text\n",
    "#BITurmas\n",
    "driver.get('https://app.powerbi.com/view?r=eyJrIjoiMWVmMTNhMzktYmQ3My00MTViLWIzODUtOTA5NjUzZTg4YWVhIiwidCI6IjYxOGE5ZWVkLWYxM2MtNDU4Ny1iODgzLTAwNWZiY2Q4N2FlZCJ9')\n",
    "sleep(6)\n",
    "soup = BeautifulSoup(driver.page_source, 'html.parser')\n",
    "element = soup.find_all('div', {'aria-valuetext': True})[-1]\n",
    "BITURMAS = element['aria-valuetext']\n",
    "#BIREMESSA\n",
    "driver.get('https://app.powerbi.com/view?r=eyJrIjoiNGVhYWFkYTYtZGYzNC00ZThlLWIwMDUtODFhNzdhYmZjMGFhIiwidCI6IjYxOGE5ZWVkLWYxM2MtNDU4Ny1iODgzLTAwNWZiY2Q4N2FlZCJ9')\n",
    "sleep(6)\n",
    "soup = BeautifulSoup(driver.page_source, 'html.parser')\n",
    "BIREMESSA = soup.find_all('tspan')[-3].text\n",
    "#PendentesPrazoVencido\n",
    "driver.get('https://app.powerbi.com/view?r=eyJrIjoiNjNkYzhlYWYtMGI3Yi00NjU5LTk2OWEtODE0MmMxZTQxYjljIiwidCI6IjYxOGE5ZWVkLWYxM2MtNDU4Ny1iODgzLTAwNWZiY2Q4N2FlZCJ9')\n",
    "sleep(6)\n",
    "soup = BeautifulSoup(driver.page_source, 'html.parser')\n",
    "PENDENTESPRAZOVENCIDO = soup.find_all('tspan')[1].text\n",
    "#BIAssuntos\n",
    "driver.get('https://app.powerbi.com/view?r=eyJrIjoiYjY3NTdhNmMtN2Q1ZS00YmQyLWJmZTUtYTIyYTQzYTAyNjYwIiwidCI6IjYxOGE5ZWVkLWYxM2MtNDU4Ny1iODgzLTAwNWZiY2Q4N2FlZCJ9')\n",
    "sleep(6)\n",
    "soup = BeautifulSoup(driver.page_source, 'html.parser')\n",
    "BIASSUNTOS = soup.find_all('tspan')[0].text\n",
    "\n",
    "with open('dados.csv', mode='w', newline='', encoding='utf-8') as file:\n",
    "    writer = csv.writer(file)\n",
    "    \n",
    "    # Cabeçalhos do CSV\n",
    "    writer.writerow(['PAINEL', 'DATA','LINK','REDE','ATUALIZAR'])\n",
    "    \n",
    "    # Escreve as variáveis em uma nova linha\n",
    "    \n",
    "    writer.writerow([\"PENDENTES DE SOLUÇÃO (Diário-1)\",PENDESOL,\"https://trt7.shinyapps.io/pendentes_de_soluo/\",\"X:\\SGE\\GABINETE\\Shiny\\PENDENTES DE SOLUÇÃO\",\"Acesse o endereço de rede. Caso já tenha configurado o ambiente, é suficiente executar o arquivo 'atualizacao.R'. Veja a documentação completa em: https://confluence.trt7.jus.br/confluence/pages/viewpage.action?pageId=89104928\"])\n",
    "    writer.writerow([\"HALO (Diário)\",HALO,\"https://app.powerbi.com/view?r=eyJrIjoiMmQ0NmE2ZjUtNjRkMi00ZjI3LWFlM2QtN2RhNGJmYTBjMjFlIiwidCI6IjYxOGE5ZWVkLWYxM2MtNDU4Ny1iODgzLTAwNWZiY2Q4N2FlZCJ9\",\"X:\\SGE\\GABINETE\\BI HALO\",\"OBS: Esse BI atualiza automaticamente pelo serviço web. Acesse o endereço de rede. Abra o arquivo 'Análise de Fluxo - PJE.pbix'.  Clique no Botão 'Atualizar'.  Clique no Botão 'Publicar' \"])\n",
    "    writer.writerow([\"HERMES (Diário)\",HERMES,\"https://app.powerbi.com/view?r=eyJrIjoiMmQ0NmE2ZjUtNjRkMi00ZjI3LWFlM2QtN2RhNGJmYTBjMjFlIiwidCI6IjYxOGE5ZWVkLWYxM2MtNDU4Ny1iODgzLTAwNWZiY2Q4N2FlZCJ9\",\"X:\\SGE\\GABINETE\\BI HERMES\",\"OBS: Esse BI atualiza automaticamente pelo serviço web. Acesse o endereço de rede. Abra o arquivo 'Painel Hermes.pbix'.  Clique no Botão 'Atualizar'.  Clique no Botão 'Publicar' \"])\n",
    "    writer.writerow([\"AÇÕES PRIORITÁRIAS PJE (Diário)\",ACOESPJE,\"https://app.powerbi.com/view?r=eyJrIjoiMmUzMDJiYTgtYjFjZS00ODVmLWIxMmUtNGFhMTc5MmIyNjAyIiwidCI6IjYxOGE5ZWVkLWYxM2MtNDU4Ny1iODgzLTAwNWZiY2Q4N2FlZCJ9\",\"X:\\SGE\\GABINETE\\BI PROCESSOS COM TRAMITAÇÃO PRIORITÁRIA PENDENTES DE BAIXA IDOSOS\", \"OBS: Esse BI atualiza automaticamente pelo serviço web. Acesse o endereço de rede. Abra o arquivo 'Processos com tramitação prioritária pendentes de baixa_17022023_PJE.pbix'.  Clique no Botão 'Atualizar'.  Clique no Botão 'Publicar'\"])\n",
    "    writer.writerow([\"AÇÕES PRIORITÁRIAS (Diário)\",ACOES,\"https://app.powerbi.com/view?r=eyJrIjoiMmUzMDJiYTgtYjFjZS00ODVmLWIxMmUtNGFhMTc5MmIyNjAyIiwidCI6IjYxOGE5ZWVkLWYxM2MtNDU4Ny1iODgzLTAwNWZiY2Q4N2FlZCJ9\",\"X:\\SGE\\GABINETE\\BI PROCESSOS COM TRAMITAÇÃO PRIORITÁRIA PENDENTES DE BAIXA IDOSOS\",\"OBS: Esse BI atualiza automaticamente pelo serviço web. Acesse o endereço de rede. Abra o arquivo 'Processos com tramitação prioritária pendentes de baixa_17022023.pbix'.  Clique no Botão 'Atualizar'.  Clique no Botão 'Publicar'\"])\n",
    "    writer.writerow([\"IGEST (Mensal)\",IGEST,\"https://app.powerbi.com/view?r=eyJrIjoiYjExZGVmZTgtNjU0NC00MDAwLWJkYzgtNThlYjQwYTJhMDNhIiwidCI6IjYxOGE5ZWVkLWYxM2MtNDU4Ny1iODgzLTAwNWZiY2Q4N2FlZCJ9\",\"X:\\SGE\\GABINETE\\BI IGEST\\igest1\",\"Acesse o endereço na rede. Execute os scripts 'tab_princ.R' e 'prepara_dataset.R'. A execução desses scripts resultará na criação dos arquivos .csv com os dados necessários para que o painel seja atualizado. Com os dados gerados, Abra o aquivo 'igest.pbix'.  Clique no Botão 'Atualizar'.  Clique no Botão 'Publicar.  \"])\n",
    "    writer.writerow([\"TRT7 EM NÚMEROS (Mensal) \",TRT7,\"https://app.powerbi.com/view?r=eyJrIjoiNTZhZTIzY2QtMGY2My00NDZkLWE4MDUtMWI3Y2ViMTRiNzQ5IiwidCI6IjYxOGE5ZWVkLWYxM2MtNDU4Ny1iODgzLTAwNWZiY2Q4N2FlZCJ9\",\"X:\\SGE\\GABINETE\\BI TRT7 EM NUMEROS ATUALIZADO\",\"Acesse o endereço de rede. Abra o arquivo 'TRT 7 EM NÚMEROS - IMPLEMENTANDO.pbix'.  Clique no Botão 'Atualizar'.  Clique no Botão 'Publicar'\"])\n",
    "    writer.writerow([\"RELATÓRIO DE DESEMPENHO IGEST (Mensal)\",RDIGEST,\"https://igest.shinyapps.io/home/\",\"X:\\SGE\\GABINETE\\Shiny\\IGest RMD\",\"Acesse o endereço na rede. Execute o arquivo 'consultas.R'. Execute o arquivo 'gerador.R'.'Mova os 112 arquivos para a pasta home dentro da pasta shinyapp: 37 html + 37 pdf + 37xlsx com os nomes da varas + o arquivos nomesvara.xlsx. Execute o Script deploy.R \"])\n",
    "    writer.writerow([\"APTOS A JULGAMENTO (Mensal)\",APTOS,\"https://app.powerbi.com/view?r=eyJrIjoiYjliODY4ZWUtOTZkYy00MjE0LWI1N2MtYzEyYTJkODRkZTJiIiwidCI6IjYxOGE5ZWVkLWYxM2MtNDU4Ny1iODgzLTAwNWZiY2Q4N2FlZCJ9\",\"X:\\SGE\\GABINETE\\BI PROCESSOS APTOS A JULGAMENTO\",\"Acesse o endereço de rede. Abra o arquivo 'Provimento_4_2018_CGJT_NEW_QUERY.pbix'.  Clique no Botão 'Atualizar'.  Clique no Botão 'Publicar'\"])\n",
    "    writer.writerow([\"MOVIMENTAÇÃO PROCESSUAL DOS ÓRGÃOS JULGADORES (Mensal)\",BITURMAS,\"https://app.powerbi.com/view?r=eyJrIjoiMWVmMTNhMzktYmQ3My00MTViLWIzODUtOTA5NjUzZTg4YWVhIiwidCI6IjYxOGE5ZWVkLWYxM2MtNDU4Ny1iODgzLTAwNWZiY2Q4N2FlZCJ9\",\"X:\\SGE\\GABINETE\\BI TURMAS\",\" Acesse o endereço de rede. Abra o arquivo 'Acompanhamento Turmas.pbix'.  Clique no Botão 'Atualizar'.  Clique no Botão 'Publicar'\"])\n",
    "    writer.writerow([\"ACOMPANHAMENTO DAS CARGAS (Diário)\",BIREMESSA,\"https://app.powerbi.com/view?r=eyJrIjoiNGVhYWFkYTYtZGYzNC00ZThlLWIwMDUtODFhNzdhYmZjMGFhIiwidCI6IjYxOGE5ZWVkLWYxM2MtNDU4Ny1iODgzLTAwNWZiY2Q4N2FlZCJ9\",\"X:\\SGE\\GABINETE\\Shiny\\BI Remessa\",\"OBS: Esse BI atualiza automaticamente pelo serviço web. Acesse o endereço de rede. Abra o arquivo 'BI Remessa.pbix'.  Clique no Botão 'Atualizar'.  Clique no Botão 'Publicar'\"])\n",
    "    writer.writerow([\"PROCESSOS PENDENTES COM O PRAZO VENCIDO(Diário-1)\",PENDENTESPRAZOVENCIDO,\"https://app.powerbi.com/view?r=eyJrIjoiNjNkYzhlYWYtMGI3Yi00NjU5LTk2OWEtODE0MmMxZTQxYjljIiwidCI6IjYxOGE5ZWVkLWYxM2MtNDU4Ny1iODgzLTAwNWZiY2Q4N2FlZCJ9\",\"X:\\SGE\\GABINETE\\BI Pendentes com o relator\",\"OBS: Esse BI atualiza automaticamente pelo serviço web. Acesse o endereço de rede. Abra o arquivo 'pendentes com o relator.pbix'.  Clique no Botão 'Atualizar'.  Clique no Botão 'Publicar'\"])\n",
    "    writer.writerow([\"RECURSOS DISTRIBUÍDOS NO 2º GRAU POR ASSUNTO (Mensal)\",BIASSUNTOS,\"https://app.powerbi.com/view?r=eyJrIjoiYjY3NTdhNmMtN2Q1ZS00YmQyLWJmZTUtYTIyYTQzYTAyNjYwIiwidCI6IjYxOGE5ZWVkLWYxM2MtNDU4Ny1iODgzLTAwNWZiY2Q4N2FlZCJ9\",\"X:\\SGE\\GABINETE\\BI ASSUNTOS\",\" Acesse o endereço de rede. Abra o arquivo 'Painel de Assuntos.pbix'.  Clique no Botão 'Atualizar'.  Clique no Botão 'Publicar' \"])\n",
    "driver.quit()\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
